In [5]:
from IPython.display import display
import mne
import pickle
import os
import pandas as pd
import numpy as np

from components.dataset import Dataset_Builder
dataset_path = "data"
dataset = Dataset_Builder(dataset_path=dataset_path)\
            .with_sampling_rate(125)\
            .with_marker(start_minute=1, stop_minute=2, segment_second=5)\
            .build()

data, labels, groups = dataset.load_data_all()
data.shape, labels.shape, groups.shape

Found: 55 files
Mean:20.509090909090908, Std:6.149272617066855
Non-stressed:16
Stressed:19
Neutral:20
number of epochs = 12.0


((420, 16, 625), (420,), (420,))

In [2]:
data, labels, groups = dataset.load_data_all()
data.shape, labels.shape, groups.shape

((700, 16, 1875), (700,), (700,))

In [5]:
a,b,c = dataset.load_data('001')
a.shape, b.shape, c.shape

((20, 16, 1875), (20,), (20,))

In [7]:
np.hstack([b,b])

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [10]:
dataset.wh

array([False,  True, False, False,  True,  True, False,  True, False,
       False, False, False,  True, False, False,  True, False, False,
       False, False,  True, False, False,  True, False,  True, False,
       False,  True, False, False,  True, False,  True, False, False,
       False,  True, False,  True, False, False, False,  True,  True,
       False, False, False,  True, False, False,  True, False,  True,
       False])

In [5]:
data, labels = dataset.load_data('001')
print(data.shape, labels.shape)

(20, 16, 1875) (20,)


In [6]:
labels

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [8]:
dataset.groups

array([0, 1, 2, 2, 1, 1, 2, 1, 2, 2, 0, 0, 1, 2, 0, 1, 0, 0, 0, 2, 1, 0,
       2, 1, 0, 1, 0, 2, 1, 2, 0, 1, 2, 1, 0, 2, 2, 1, 2, 1, 0, 0, 2, 1,
       1, 0, 2, 2, 1, 2, 2, 1, 0, 1, 2])

In [9]:
print(dataset.start_sample)
print(dataset.stop_sample)
print(dataset.step_sample)
data[:, dataset.start_sample:dataset.stop_sample].shape

7500
22500
1875


(16, 15000)

In [17]:
data = dataset.load_data('001')
# We skip the first marker becase 
data = np.split(data[:, dataset.start_sample:dataset.stop_sample], dataset._expected_epochs_number, axis=1)
print(data[0].shape)
data = [np.expand_dims(data,axis=0) for data in data]
data = np.vstack(data)
data.shape

(16, 1875)


(8, 16, 1875)

In [ ]:
# [np.array(16,125*segment),...] => len(data.shape[1]/segment)
data = [np.expand_dims(data,axis=0) for data in data]
# [np.array(1,16,125*segment),...] => len(data.shape[1]/segment)
data = np.vstack(data)
# (len(data.shape[1]/segment) , 16 , 125*segment )

assert data.shape[0] == dataset._expected_epochs_number, f"data.shape={data.shape}. Expect the first dimension to be {dataset._expected_epochs_number}"

return data

In [12]:
import numpy as np
a = np.arange(0,200).reshape(2,10,10)
a = a.ravel()
a

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 18

In [14]:
a.reshape(2,20,5)

array([[[  0,   1,   2,   3,   4],
        [  5,   6,   7,   8,   9],
        [ 10,  11,  12,  13,  14],
        [ 15,  16,  17,  18,  19],
        [ 20,  21,  22,  23,  24],
        [ 25,  26,  27,  28,  29],
        [ 30,  31,  32,  33,  34],
        [ 35,  36,  37,  38,  39],
        [ 40,  41,  42,  43,  44],
        [ 45,  46,  47,  48,  49],
        [ 50,  51,  52,  53,  54],
        [ 55,  56,  57,  58,  59],
        [ 60,  61,  62,  63,  64],
        [ 65,  66,  67,  68,  69],
        [ 70,  71,  72,  73,  74],
        [ 75,  76,  77,  78,  79],
        [ 80,  81,  82,  83,  84],
        [ 85,  86,  87,  88,  89],
        [ 90,  91,  92,  93,  94],
        [ 95,  96,  97,  98,  99]],

       [[100, 101, 102, 103, 104],
        [105, 106, 107, 108, 109],
        [110, 111, 112, 113, 114],
        [115, 116, 117, 118, 119],
        [120, 121, 122, 123, 124],
        [125, 126, 127, 128, 129],
        [130, 131, 132, 133, 134],
        [135, 136, 137, 138, 139],
        [140, 141,

In [16]:
band_names = ['delta','theta','alpha','beta','gamma','slow','beta_low']
band_names.index('delta')

0

In [3]:
import numpy as np
np.arange(2,16*8,16)

array([  2,   9,  16,  23,  30,  37,  44,  51,  58,  65,  72,  79,  86,
        93, 100, 107, 114, 121])

In [16]:
import numpy as np
from sklearn.preprocessing import StandardScaler
def standardize(data: np.ndarray) -> np.ndarray:
    '''data: a numpy array of shape (n_samples, n_features)
    '''
    ori_data = data.copy()
    ori_data = check_float(ori_data)
    ori_data = ori_data.T
    for index, row in enumerate(ori_data):
        mean = row.mean()
        std = row.std()
        row = (row - mean) / std
        ori_data[index] = row
        # print(row)

    return ori_data.T

def check_float(data) -> np.ndarray:
    if(data.dtype == np.int64): data = data.astype(np.float64)
    return data

In [33]:
data = np.tile(np.arange(0,10,1).reshape(10,1), (1,5)) * [0.1, 1, 0, 100 , 1000] + [1,2,3,4,5]
print(data)

[[1.000e+00 2.000e+00 3.000e+00 4.000e+00 5.000e+00]
 [1.100e+00 3.000e+00 3.000e+00 1.040e+02 1.005e+03]
 [1.200e+00 4.000e+00 3.000e+00 2.040e+02 2.005e+03]
 [1.300e+00 5.000e+00 3.000e+00 3.040e+02 3.005e+03]
 [1.400e+00 6.000e+00 3.000e+00 4.040e+02 4.005e+03]
 [1.500e+00 7.000e+00 3.000e+00 5.040e+02 5.005e+03]
 [1.600e+00 8.000e+00 3.000e+00 6.040e+02 6.005e+03]
 [1.700e+00 9.000e+00 3.000e+00 7.040e+02 7.005e+03]
 [1.800e+00 1.000e+01 3.000e+00 8.040e+02 8.005e+03]
 [1.900e+00 1.100e+01 3.000e+00 9.040e+02 9.005e+03]]


In [34]:
standardize(data.copy())

/tmp/ipykernel_15811/2571321800.py:12: RuntimeWarning: invalid value encountered in true_divide
  row = (row - mean) / std


array([[-1.5666989 , -1.5666989 ,         nan, -1.5666989 , -1.5666989 ],
       [-1.21854359, -1.21854359,         nan, -1.21854359, -1.21854359],
       [-0.87038828, -0.87038828,         nan, -0.87038828, -0.87038828],
       [-0.52223297, -0.52223297,         nan, -0.52223297, -0.52223297],
       [-0.17407766, -0.17407766,         nan, -0.17407766, -0.17407766],
       [ 0.17407766,  0.17407766,         nan,  0.17407766,  0.17407766],
       [ 0.52223297,  0.52223297,         nan,  0.52223297,  0.52223297],
       [ 0.87038828,  0.87038828,         nan,  0.87038828,  0.87038828],
       [ 1.21854359,  1.21854359,         nan,  1.21854359,  1.21854359],
       [ 1.5666989 ,  1.5666989 ,         nan,  1.5666989 ,  1.5666989 ]])

In [35]:
scaler = StandardScaler()
scaler.fit_transform(data.copy())

array([[-1.5666989 , -1.5666989 ,  0.        , -1.5666989 , -1.5666989 ],
       [-1.21854359, -1.21854359,  0.        , -1.21854359, -1.21854359],
       [-0.87038828, -0.87038828,  0.        , -0.87038828, -0.87038828],
       [-0.52223297, -0.52223297,  0.        , -0.52223297, -0.52223297],
       [-0.17407766, -0.17407766,  0.        , -0.17407766, -0.17407766],
       [ 0.17407766,  0.17407766,  0.        ,  0.17407766,  0.17407766],
       [ 0.52223297,  0.52223297,  0.        ,  0.52223297,  0.52223297],
       [ 0.87038828,  0.87038828,  0.        ,  0.87038828,  0.87038828],
       [ 1.21854359,  1.21854359,  0.        ,  1.21854359,  1.21854359],
       [ 1.5666989 ,  1.5666989 ,  0.        ,  1.5666989 ,  1.5666989 ]])

In [21]:
data

array([[0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3],
       [4, 4, 4, 4, 4],
       [5, 5, 5, 5, 5],
       [6, 6, 6, 6, 6],
       [7, 7, 7, 7, 7],
       [8, 8, 8, 8, 8],
       [9, 9, 9, 9, 9]])

In [83]:
import re
def get_10_cv(file_path):
    lines = []
    with open(file_path, 'r') as f:
        # last_line = f.readlines()[-1]
        for line in f:
            if(re.search('grid.best_params_',line)):
                lines.append(line)
    return lines

def get_accs(best_rows):
    # 26-06-2022 16:09:10|ml.py:44|INFO|3/10|grid.best_params_={'C': 1000000.0, 'gamma': 1e-09, 'kernel': 'rbf', 'max_iter': 1000}, grid.best_score_=0.6678240740740741, grid.best_index_=28, acc=0.4375, time=2.2673180103302
    accs = []
    for line in best_rows:
        acc = float(line[line.index('acc=') + len('acc='): line.index('time=')-2])
        accs.append(acc)
    return accs
        

best_rows = get_10_cv('../cv_results/125-1-3-15/ml.log')
accs = get_accs(best_rows)
print(len(best_rows))

5


In [84]:
accs

[0.5, 0.3125, 0.4375, 0.59375, 0.4166666666666667]

In [2]:
import logging
def _init_logger(name:str, filename:str, level:int=logging.INFO):
    logger = logging.getLogger(name)
    logger.setLevel(level)
    formatter = logging.Formatter('%(asctime)s|%(filename)s:%(lineno)d|%(levelname)s|%(message)s')
    formatter.datefmt = '%d-%m-%Y %H:%M:%S'

    # Handler
    consoleHandler = logging.StreamHandler(sys.stdout)
    consoleHandler.setFormatter(formatter)
    fileHandler = logging.FileHandler(filename=filename)
    fileHandler.setFormatter(formatter)

    # Add Handler
    logger.addHandler(consoleHandler)
    logger.addHandler(fileHandler)

In [4]:
_init_logger('ml', 'ml.log')

In [5]:
logger = logging.getLogger('ml')

In [14]:
a = logger.handlers[1]
type(a)

logging.FileHandler

In [22]:
a.baseFilename

'/root/projects/3-DoubleCrossValidation/ml.log'

In [21]:
type(a) == logging.StreamHandler

False

In [17]:
logging.StreamHandler

logging.StreamHandler

In [3]:
from components.dataset import Dataset_Builder
dataset = Dataset_Builder(dataset_path='data')\
            .with_sampling_rate(sampling_rate=125)\
            .with_marker(start_minute=0, 
                    stop_minute=5, 
                    segment_second=15)\
            .build()
data, labels, groups = dataset.load_data_all()
data.shape, labels.shape, groups.shape

((700, 16, 1875), (700,), (700,))

In [16]:
# https://raphaelvallat.com/bandpower.html
from scipy.signal import welch
import numpy as np
# Compute the modified periodogram (Welch)
freqs, psd = welch(data, 125, nperseg=250)
freqs.shape, psd.shape

((126,), (700, 16, 126))

In [32]:
bands  = {'delta': [1,3],
'theta': [4,7],
'alpha': [8,12],
'beta': [13,30],
'gamma': [25,43],
'slow': [4,13],
'beta_low': [13,17]}
from scipy.integrate import simps
temp = []
for name, (low, high) in bands.items():
    idx_band = np.logical_and(freqs >= low, freqs <= high)
    bp = simps(psd[:,:,idx_band], dx=freqs[1] - freqs[0])
    temp.append(bp)

np.hstack(temp).shape

(700, 112)

In [41]:
(temp == abs(temp)).all()

True

In [23]:
bp.shape

(700, 16)

In [38]:
np.isnan(temp).any()

False