In [1]:
from utils import *
import pandas as pd
import mne
from glob import glob
import numpy as np
import matplotlib.pyplot as plt
from tqdm.notebook import tqdm
from sklearn.preprocessing import normalize, StandardScaler
plt.style.use('seaborn-whitegrid')

In [2]:
def get_threshold(scores):
    scores = np.array(scores)
    lower_threshold = scores.mean() - (scores.std()/2)
    upper_threshold = scores.mean() + (scores.std()/2)
    return scores.mean(), (lower_threshold,upper_threshold)

def get_stress_type(score, grade):
    """ Non-stress (0): score < lower_threshold
        Neutral    (1): lower_threshold <= score <= upper_threshold
        Stress     (2): score > lower_threshold """
    if(score < grade[0]):
        return 0
    elif(score <= grade[1]):
        return 1
    elif(score > grade[1]):
        return 2

def PSS_printer(PSS):
    # peak at info
    temp = PSS.popitem()
    PSS[temp[0]] = temp[1]
    column = list(temp[1].keys())
    space = "\t\t"
    print(f"Name{space}",f"{space}".join(column),sep="" )
    print("="*60)
    for name, info in PSS.items():
        print(f"{name}{space}",sep="",end="")
        for col in column:
            print(f"{info[col]}{space}",end="")

        print()


TYPE_DEF = {0:'Non-Stress', 1:'Neutral', 2: 'Stress'}

In [3]:
PSS = dict()
scores = []
with open('./PSS_scores.csv','r') as f:
    f.readline() # skip header
    for line in f.readlines(): 
        name,score = line.split(',')
        PSS[name] = {'score':int(score)}
        scores.append(int(score))

mean, grade = get_threshold(scores)
# print(f"Total={len(PSS)} | Mean={mean} | Lower Thres={grade[0]} | Higher Thres={grade[1]}")

type_count = {0:0, 1:0, 2:0}
for name, dict_info in PSS.items():
    label = get_stress_type(dict_info['score'], grade)
    dict_info['type'] = label
    dict_info['type_definition'] = TYPE_DEF[label]
    type_count[label] = type_count[label] + 1

# print(f"Non Stress={type_count[0]} | Neutral={type_count[1]} | Stress={type_count[2]}")

# PSS_printer(PSS)

In [4]:
sampling_rate = 125 #Hz
files = glob(f"data/*.csv")
for f in tqdm(files):
    name = f.split('/')[1].split('__')[0]
    pd_raw = pd.read_csv(f, dtype={'Marker':str})
    pd_raw = pd_raw.drop(columns='timestamps')
    raw = dataframe_to_raw(pd_raw, sfreq=sampling_rate)
    PSS[name]['raw'] = raw
    # print(f"{name} | time: {len(pd_raw)/125}")

  0%|          | 0/56 [00:00<?, ?it/s]

KeyboardInterrupt: 

In [5]:
# save(PSS,"PSS")

PSS = load("PSS")

In [6]:
for name, info in tqdm(PSS.items()):
    raw = info['raw']
    raw.filter(l_freq=1,h_freq=None, method='iir', iir_params={'order':3.0, 'ftype':'butter'}, verbose=False) # Slow drift
    raw.notch_filter(freqs=[50])
    # epochs = mne.Epochs(raw, np.array([[125*60*1, 0, 1]]), tmin=0, tmax=30, baseline=(0,30), verbose=False)
    # print(name)
    # a = epochs.plot_psd(picks=['F3','F4','T3','T4'])
    # print("="*40)

  0%|          | 0/55 [00:00<?, ?it/s]

In [7]:
def get_freq(PSS):
    # peak at info
    temp = PSS.popitem()
    PSS[temp[0]] = temp[1]
    raw = temp[1]['raw']
    power,freq = mne.time_frequency.psd_welch(raw,n_fft=125, verbose=True)
    return freq

freq = get_freq(PSS)
print(freq)

Effective window size : 1.000 (s)
[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17.
 18. 19. 20. 21. 22. 23. 24. 25. 26. 27. 28. 29. 30. 31. 32. 33. 34. 35.
 36. 37. 38. 39. 40. 41. 42. 43. 44. 45. 46. 47. 48. 49. 50. 51. 52. 53.
 54. 55. 56. 57. 58. 59. 60. 61. 62.]


In [8]:
band_names = np.array(['Delta', 'Theta', 'Alpha', 'Beta', 'Gamma', 'Slow', 'Low_beta'])
filter_list = [[1,3],[4,7],[8,12],[13,30],[30,43], [4,13], [13,17]]
bands = []
for filt in filter_list:
    pt = np.argwhere((freq >= filt[0]) & (freq <= filt[1])).reshape(-1)
    bands.append(pt)
bands = np.array(bands)
print(bands)

[array([1, 2, 3]) array([4, 5, 6, 7]) array([ 8,  9, 10, 11, 12])
 array([13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29,
        30])
 array([30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43])
 array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13])
 array([13, 14, 15, 16, 17])]


/tmp/ipykernel_38710/3256231302.py:7: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  bands = np.array(bands)


In [9]:
# features = None
csv = None
names = []
for name,info in PSS.items():
    names.append(name)
    raw = info['raw']
    row = None
    feature = None
    slow, gamma = None, None
    a_f3, a_f4 = None, None
    a_t7, a_t8 = None, None
    b_f3, b_f4 = None, None
    b_t7, b_t8 = None, None
    # epochs = mne.Epochs(raw, np.array([[125*60*1, 0, 1]]), tmin=0, tmax=30, baseline=(0,30), verbose=False)
    for index, band in enumerate(bands):
        power,freq = mne.time_frequency.psd_welch(raw,n_fft=125, verbose=False)
        power = power.squeeze()
        power = 10 * np.log10(power)
        data = power[::,band].mean(axis=1).reshape(1,-1)
        # print(f"{data.shape=}")

        if(type(row) == type(None)): row = data.copy()
        else: row = np.concatenate([row,data.copy()], axis=1)

        # print(f"{row.shape=}")
        # for asym
        if(band_names[index] == 'Alpha'):
            a_f3 = data[:,raw.ch_names.index('F3')]
            a_f4 = data[:,raw.ch_names.index('F4')]
            # We use t3 as t7 and t4 as t8
            a_t7 = data[:,raw.ch_names.index('T3')]
            a_t8 = data[:,raw.ch_names.index('T4')]
        if(band_names[index] == 'Beta'):
            b_f3 = data[:,raw.ch_names.index('F3')]
            b_f4 = data[:,raw.ch_names.index('F4')]
            # We use t3 as t7 and t4 as t8
            b_t7 = data[:,raw.ch_names.index('T3')]
            b_t8 = data[:,raw.ch_names.index('T4')]

        ####### Mean for visualization #######
        data = data.mean().reshape(1,-1)
        # for relative gamma
        if(band_names[index] == 'Slow'): slow = data
        if(band_names[index] == 'Gamma'): gamma = data

        if(type(feature) == type(None)): feature = data
        else: feature = np.concatenate([feature, data], axis=1)
    # print(feature.shape)
    # the eighth feature: relative gamma is slow/gamma
    relative_gamma = slow/gamma
    feature = np.concatenate([feature, relative_gamma], axis=1)
    # The asymetry
    alpha_frontal = ((a_f4 - a_f3) / (a_f4 + a_f3)).reshape(1,-1)
    feature = np.concatenate([feature, alpha_frontal], axis=1)
    # alpha_temporal
    alpha_temporal = ((a_t8 - a_t7) / (a_t8 + a_t7)).reshape(1,-1)
    feature = np.concatenate([feature, alpha_temporal], axis=1)
    # alpha_asymmetry
    alpha_asymmetry = alpha_frontal + alpha_temporal
    feature = np.concatenate([feature, alpha_asymmetry], axis=1)
    # beta_frontal
    beta_frontal = ((b_f4 - b_f3) / (b_f4 + b_f3)).reshape(1,-1)
    feature = np.concatenate([feature, beta_frontal], axis=1)
    # beta_temporal
    beta_temporal = ((b_t8 - b_t7) / (b_t8 + b_t7)).reshape(1,-1)
    feature = np.concatenate([feature, beta_temporal], axis=1)

    row = np.concatenate([row, relative_gamma, alpha_frontal, alpha_temporal, alpha_asymmetry, beta_frontal, beta_temporal], axis=1)
    # print(slow/gamma)
    # print(feature.shape)
    # print(feature)
    info['feature'] = feature
    if(type(csv) == type(None)): csv = row
    else: csv = np.concatenate([csv,row], axis=0)
    print(f"{csv.shape=}")
    # break
    # if(type(features) == type(None)): features = feature
    # else: features = np.concatenate([features, feature], axis=0)
# print(features.shape)


csv.shape=(1, 118)
csv.shape=(2, 118)
csv.shape=(3, 118)
csv.shape=(4, 118)
csv.shape=(5, 118)
csv.shape=(6, 118)
csv.shape=(7, 118)
csv.shape=(8, 118)
csv.shape=(9, 118)
csv.shape=(10, 118)
csv.shape=(11, 118)
csv.shape=(12, 118)
csv.shape=(13, 118)
csv.shape=(14, 118)
csv.shape=(15, 118)
csv.shape=(16, 118)
csv.shape=(17, 118)
csv.shape=(18, 118)
csv.shape=(19, 118)
csv.shape=(20, 118)
csv.shape=(21, 118)
csv.shape=(22, 118)
csv.shape=(23, 118)
csv.shape=(24, 118)
csv.shape=(25, 118)
csv.shape=(26, 118)
csv.shape=(27, 118)
csv.shape=(28, 118)
csv.shape=(29, 118)
csv.shape=(30, 118)
csv.shape=(31, 118)
csv.shape=(32, 118)
csv.shape=(33, 118)
csv.shape=(34, 118)
csv.shape=(35, 118)
csv.shape=(36, 118)
csv.shape=(37, 118)
csv.shape=(38, 118)
csv.shape=(39, 118)
csv.shape=(40, 118)
csv.shape=(41, 118)
csv.shape=(42, 118)
csv.shape=(43, 118)
csv.shape=(44, 118)
csv.shape=(45, 118)
csv.shape=(46, 118)
csv.shape=(47, 118)
csv.shape=(48, 118)
csv.shape=(49, 118)
csv.shape=(50, 118)
csv.shape

In [10]:
with open("feature_alpha_temporal.csv","w") as f:
    # print(raw.ch_names[:-1])
    # print(band_names)
    header = ["name"]
    for band_name in band_names:
        for ch_name in raw.ch_names[:-1]:
            header.append(f"{ch_name}_{band_name}")
    f.write(",".join(header))


In [11]:
np.savetxt("foo.csv", csv, delimiter=",")

In [12]:
print(names)

['fabby', 'bas', 'flm', 'mind', 'taew', 'MJ', 'nopphon', 'boss', 'film', 'new', 'nice', 'nuclear', 'pang', 'prin', 'amp', 'beau', 'dt', 'int', 'minkhant', 'sam', 'yong', 'aui', 'bank', 'dream', 'eiyu', 'ice', 'job', 'kee', 'miiw', 'noey', 'pear', 'por', 'satya', 'shin', 'suyo', 'tom', 'yee', 'aun', 'bam', 'beer', 'cedric', 'fahmai', 'gon', 'harold', 'kant', 'kao', 'mu', 'nisit', 'pla', 'ploy', 'poon', 'praewphan', 's', 'younten', 'tor']


In [14]:
a = pd.read_csv("feature_alpha_temporal.csv")
a

name   Fp1_Delta   Fp2_Delta    F3_Delta    F4_Delta    F7_Delta  \
0       fabby -108.142032 -106.856941 -113.034416 -114.015930 -110.863628   
1         bas -112.144357 -111.263373 -115.079108 -114.881152 -110.102575   
2         flm -107.828217 -106.708678 -108.975226 -108.736270 -105.780501   
3        mind -105.730249 -107.716302 -112.755134 -112.884600 -110.551033   
4        taew -110.371056 -110.441711 -113.232092 -113.550211 -106.328417   
5          MJ -106.771660 -106.695414 -100.552533  -99.913268 -106.643644   
6     nopphon -108.439858 -108.327284 -109.118434 -109.325013 -108.023946   
7        boss -100.835945 -100.732043 -100.159876 -100.278665  -99.497625   
8        film -106.109298 -105.330771 -105.883335 -105.088071 -105.796734   
9         new -108.680381 -108.627466 -110.171547  -86.631531 -108.721693   
10       nice -108.748366 -108.523773 -108.055298 -106.840319 -109.037631   
11    nuclear -109.646302 -110.479791 -106.036139 -108.777546 -104.170266   
12       pang -108.330749 -108.209472 -105.021960 -109.706365 -106.061569   
13       prin -107.525587 -107.132251 -108.726584 -108.038537 -105.228084   
14        amp -110.369406 -108.772052 -113.486551 -110.636608 -109.707221   
15       beau -102.857324 -111.285884  -96.016487 -111.176485 -112.899695   
16         dt -108.467414 -108.906192 -112.562175 -106.707064 -103.009439   
17        int -108.845999 -110.573592 -106.204288 -106.098985 -107.357558   
18   minkhant -110.532883 -110.371970 -114.102627 -111.201253 -110.674758   
19        sam -108.035434 -107.358032 -108.828246 -108.057735 -107.591015   
20       yong -105.595027 -108.324872 -114.080870 -112.985716 -101.343125   
21        aui -112.680896 -113.426034 -105.562198 -115.148567 -103.549585   
22       bank -108.319354 -108.464846 -109.315391 -106.549970 -104.902960   
23      dream -113.458736 -112.471305 -105.203380 -116.724845 -114.439039   
24       eiyu -110.409867 -109.853559 -112.169638 -112.160626 -105.197058   
25        ice -108.249887 -107.569122 -112.010780 -111.580857 -110.267322   
26        job -106.418940 -106.180156 -110.003662 -105.171955 -105.291560   
27        kee -100.096602  -99.943746  -99.214228  -99.999971  -99.543631   
28       miiw -106.614058 -107.062244 -108.025058 -111.341381 -104.224688   
29       noey -105.344802 -106.473155 -103.607184 -107.771412 -100.490447   
30       pear -110.010924 -111.094732 -110.213923 -111.598851 -102.114626   
31        por -107.443741 -108.596350 -111.971972 -111.420437 -107.393466   
32      satya -105.261391 -106.165704 -108.202274 -108.061763 -104.353583   
33       shin -108.268285 -110.527684 -104.203603 -104.926664 -105.009974   
34       suyo -107.227401 -106.825612 -105.492487  -97.248348  -95.812493   
35        tom -105.499166 -107.571602 -102.726555 -107.057860 -109.153885   
36        yee -110.253136 -106.581644 -114.214778 -114.369205 -112.489947   
37        aun -106.934415 -106.435087 -112.560767 -111.736690 -105.296830   
38        bam -106.180866 -106.921952 -113.334272 -114.002241 -110.850344   
39       beer -112.264493 -112.813007 -114.135079 -114.566754 -111.433208   
40     cedric -104.465192 -103.762176 -111.784289 -106.654058 -106.454054   
41     fahmai -104.594263 -104.076158 -107.033450 -105.735148 -105.774455   
42        gon -107.558913 -107.182931 -107.129261 -107.517473 -106.582749   
43     harold -106.782334 -106.236084 -105.492762 -105.027739 -106.868935   
44       kant -110.286895 -109.967783 -114.229279 -113.468664 -111.307100   
45        kao -109.511644 -109.878636 -112.555601 -113.360477 -107.081969   
46         mu -112.744169 -108.739682 -115.412479 -113.026254 -106.241180   
47      nisit -108.073643 -110.812667 -114.921410 -113.585873 -108.853839   
48        pla -105.439640 -104.131570 -107.788536 -110.298990 -108.622922   
49       ploy -107.260010 -107.028364  -97.590299 -107.330411 -106.630254   
50       poon -107.176258 -105.820719 -109.630573 -102.664938 -105.200478   
51  p

In [81]:
b = a.T[:10].T.copy()

In [84]:
b.to_csv("feature_less.csv")